CREATE DATABASE JOBSTER;

USE JOBSTER;

CREATE TABLE USER (
    user_id INT(50) NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    enabled BOOLEAN,
    PRIMARY KEY(user_id)
);

CREATE TABLE USER_ROLE (
	user_role_id INT(50) NOT NULL AUTO_INCREMENT,
	user_id INT(50) NOT NULL,
	role VARCHAR(50) NOT NULL,
	PRIMARY KEY (user_role_id),
	FOREIGN KEY (user_id) REFERENCES USER(user_id)
);

CREATE TABLE COMPANY_DATA(
	COMPANY_ID INT NOT NULL AUTO_INCREMENT,
	COMPANY_NAME VARCHAR(45) NOT NULL,
	PRIMARY KEY(COMPANY_ID)
);

CREATE TABLE SEEKER_DETAIL(
	USER_ID INT(50) NOT NULL,
	LOCATION VARCHAR(50) NOT NULL,
	SKILL VARCHAR(50) NOT NULL,
	RESUME_URL VARCHAR(125) NOT NULL,
	EXPERIENCE INT NOT NULL,
	FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);


CREATE TABLE RECRUITER_DETAIL(
	COMPANY_ID INT NOT NULL,
	USER_ID INT(50) NOT NULL,
	DESIGNATION VARCHAR(20) NOT NULL,
	FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY_DATA(COMPANY_ID),
	FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE VACANCY(
	VACANCY_ID INT NOT NULL AUTO_INCREMENT,
	RECRUITER_ID INT(50) NOT NULL,
	COMPANY_ID INT NOT NULL,
	VACANCY_COUNT INT NULL,
	LOCATION VARCHAR(10) NOT NULL,
	SKILL VARCHAR(10) NOT NULL,
	EXPERIENCE INT NOT NULL,
	PRIMARY KEY(VACANCY_ID),
	FOREIGN KEY(RECRUITER_ID) REFERENCES RECRUITER_DETAIL(USER_ID),
	FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY_DATA(COMPANY_ID)
);

CREATE TABLE APPLIED_JOBS(
	VACANCY_ID INT NOT NULL,
	EMPLOYEE_ID INT NOT NULL,
	FOREIGN KEY(VACANCY_ID) REFERENCES VACANCY(VACANCY_ID),
	FOREIGN KEY(EMPLOYEE_ID) REFERENCES SEEKER_DETAIL(USER_ID)
);
_______________________________________________________________________________________________________________________________
_______________________________________________________________________________________________________________________________