USE aqSY3khsjM;

CREATE TABLE USER_CREDENTIAL(
USERNAME VARCHAR(20) NOT NULL, 
PASSWORD CHAR(40) NOT NULL,
ROLE CHAR(10) NOT NULL,
PRIMARY KEY(USERNAME)
);

CREATE TABLE COMPANY_DATA(
COMPANY_ID INT NOT NULL AUTO_INCREMENT,
COMPANY_NAME VARCHAR(10) NOT NULL,
PRIMARY KEY(COMPANY_ID)
);

CREATE TABLE EMPLOYEE_DETAIL(
EMPLOYEE_ID INT NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(20) NOT NULL,
LOCATION VARCHAR(20) NOT NULL,
SKILL VARCHAR(20) NOT NULL,
RESUME_URL VARCHAR(125) NOT NULL,
EXPERIENCE INT NOT NULL,
PRIMARY KEY(EMPLOYEE_ID),
FOREIGN KEY(USERNAME) REFERENCES USER_CREDENTIAL(USERNAME)
);

CREATE TABLE RECRUITER_DETAIL(
COMPANY_ID INT NOT NULL,
USERNAME VARCHAR(20) NOT NULL,
DESIGNATION VARCHAR(20) NOT NULL,
FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY_DATA(COMPANY_ID),
FOREIGN KEY(USERNAME) REFERENCES USER_CREDENTIAL(USERNAME)
);

CREATE TABLE VACANCY(
COMPANY_ID INT NOT NULL,
VACANCY_COUNT INT NULL,
LOCATION VARCHAR(10) NOT NULL,
SKILL VARCHAR(10) NOT NULL,
EXPERIENCE INT NOT NULL,
FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY_DATA(COMPANY_ID)
);

ALTER TABLE EMPLOYEE_DETAIL MODIFY COLUMN EMPLOYEE_ID INT NOT NULL AUTO_INCREMENT;

DROP TABLE USER_CREDENTIAL;
DROP TABLE EMPLOYEE_DETAIL;
DROP TABLE RECRUITER_DETAIL;

CREATE  TABLE users (
  username VARCHAR(45) NOT NULL ,
  password VARCHAR(45) NOT NULL ,
  enabled TINYINT NOT NULL DEFAULT 1 ,
  PRIMARY KEY (username));

CREATE TABLE user_roles (
  user_role_id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(45) NOT NULL,
  role varchar(45) NOT NULL,
  PRIMARY KEY (user_role_id),
  UNIQUE KEY uni_username_role (role,username),
  KEY fk_username_idx (username),
  CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username));


INSERT INTO users(username,password,enabled)
VALUES ('ashutoshaneja','ashu123', true);
INSERT INTO users(username,password,enabled)
VALUES ('Sandeep','123', true);

INSERT INTO user_roles (username, role)
VALUES ('ashutoshaneja', 'ROLE_SEEKER');
INSERT INTO user_roles (username, role)
VALUES ('Sandeep', 'ROLE_RECRUITER');
