USE aqSY3khsjM;

CREATE DATABASE JOBSTER;

USE JOBSTER;

CREATE TABLE USER (
    user_id INT(50) NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    enabled BOOLEAN,
    PRIMARY KEY(user_id)
);

CREATE TABLE USER_ROLE (
  user_role_id INT(50) NOT NULL AUTO_INCREMENT,
  user_id INT(50) NOT NULL,
  role VARCHAR(50) NOT NULL,
  PRIMARY KEY (user_role_id),
  FOREIGN KEY (user_id) REFERENCES USER(user_id)
);

INSERT INTO USER(username,PASSWORD,enabled)
VALUES ('ashutoshaneja','ashu123', TRUE);
INSERT INTO USER(username,PASSWORD,enabled)
VALUES ('Sandeep','123', TRUE);

INSERT INTO USER_ROLE (user_id, role)
VALUES (1, 'ROLE_SEEKER');
INSERT INTO USER_ROLE (user_id, role)
VALUES (2, 'ROLE_RECRUITER');

/*CREATE  TABLE users (
  username VARCHAR(45) NOT NULL ,
  password VARCHAR(45) NOT NULL ,
  enabled TINYINT NOT NULL DEFAULT 1 ,
  PRIMARY KEY (username));

CREATE TABLE user_roles (
  user_role_id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(45) NOT NULL,
  role varchar(45) NOT NULL,
  PRIMARY KEY (user_role_id),
  UNIQUE KEY uni_username_role (role,username),
  KEY fk_username_idx (username),
  CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username));*/


CREATE TABLE COMPANY_DATA(
COMPANY_ID INT NOT NULL AUTO_INCREMENT,
COMPANY_NAME VARCHAR(45) NOT NULL,
PRIMARY KEY(COMPANY_ID)
);

CREATE TABLE SEEKER_DETAIL(
EMPLOYEE_ID INT NOT NULL AUTO_INCREMENT,
USER_ID INT(50) NOT NULL,
LOCATION VARCHAR(50) NOT NULL,
SKILL VARCHAR(50) NOT NULL,
RESUME_URL VARCHAR(125) NOT NULL,
EXPERIENCE INT NOT NULL,
PRIMARY KEY(EMPLOYEE_ID),
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);


CREATE TABLE RECRUITER_DETAIL(
COMPANY_ID INT NOT NULL,
USER_ID INT(50) NOT NULL,
DESIGNATION VARCHAR(20) NOT NULL,
FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY_DATA(COMPANY_ID),
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE VACANCY(
VACANCY_ID INT NOT NULL AUTO_INCREMENT,
USER_ID INT(50) NOT NULL,
COMPANY_ID INT NOT NULL,
VACANCY_COUNT INT NULL,
LOCATION VARCHAR(10) NOT NULL,
SKILL VARCHAR(10) NOT NULL,
EXPERIENCE INT NOT NULL,
PRIMARY KEY(VACANCY_ID),
FOREIGN KEY(USER_ID) REFERENCES RECRUITER_DETAIL(USER_ID),
FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY_DATA(COMPANY_ID)
);

CREATE TABLE APPLIED_JOBS(
VACANCY_ID INT NOT NULL,
EMPLOYEE_ID INT NOT NULL,
FOREIGN KEY(VACANCY_ID) REFERENCES VACANCY(VACANCY_ID),
FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE_DETAIL(USER_ID)
);

ALTER TABLE EMPLOYEE_DETAIL MODIFY COLUMN EMPLOYEE_ID INT NOT NULL AUTO_INCREMENT;

ALTER TABLE USER MODIFY COLUMN PASSWORD VARCHAR(60) NOT NULL;

DROP TABLE USER_CREDENTIAL;
DROP TABLE EMPLOYEE_DETAIL;
DROP TABLE RECRUITER_DETAIL;

_______________________________________________________________________________________________________________________________

CREATE TABLE APPLIED_JOBS(
VACANCY_ID INT NOT NULL,
EMPLOYEE_ID INT NOT NULL,
FOREIGN KEY(VACANCY_ID) REFERENCES VACANCY(VACANCY_ID),
FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE_DETAIL(EMPLOYEE_ID)
);

DESC APPLIED_JOBS;

DESC users;

DROP TABLE user_role;
DROP TABLE USER;


CREATE TABLE VACANCY(
VACANCY_ID INT NOT NULL AUTO_INCREMENT,
RECRUITER_ID INT(50) NOT NULL,
COMPANY_ID INT NOT NULL,
VACANCY_COUNT INT NULL,
LOCATION VARCHAR(10) NOT NULL,
SKILL VARCHAR(10) NOT NULL,
EXPERIENCE INT NOT NULL,
PRIMARY KEY(VACANCY_ID),
FOREIGN KEY(RECRUITER_ID) REFERENCES RECRUITER_DETAIL(USER_ID),
FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY_DATA(COMPANY_ID)
);

DROP TABLE vacancy;


CREATE TABLE APPLIED_JOBS(
VACANCY_ID INT(50) NOT NULL,
EMPLOYEE_ID INT(50) NOT NULL,
FOREIGN KEY(VACANCY_ID) REFERENCES VACANCY(VACANCY_ID),
FOREIGN KEY(EMPLOYEE_ID) REFERENCES SEEKER_DETAIL(USER_ID)
);


ALTER TABLE USER MODIFY COLUMN PASSWORD VARCHAR(60) NOT NULL;
